// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzQS-xL8V1LqOpkTj-MbrQRC9XYhnMZ4',
    appId: '1:990863299881:web:12cd4d5b53767cb6a95338',
    messagingSenderId: '990863299881',
    projectId: 'aion-5a2c7',
    authDomain: 'aion-5a2c7.firebaseapp.com',
    storageBucket: 'aion-5a2c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALKB8Nvhl7QJwjpJK5XT4ruLJ0yUOECFM',
    appId: '1:990863299881:android:8fa5f52e846c3f11a95338',
    messagingSenderId: '990863299881',
    projectId: 'aion-5a2c7',
    storageBucket: 'aion-5a2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBotBFzKqCYeq4m1i2Vx0E_KzXR04A4Y',
    appId: '1:990863299881:ios:c99748b4389d4499a95338',
    messagingSenderId: '990863299881',
    projectId: 'aion-5a2c7',
    storageBucket: 'aion-5a2c7.firebasestorage.app',
    iosBundleId: 'com.rejrak.wos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKBotBFzKqCYeq4m1i2Vx0E_KzXR04A4Y',
    appId: '1:990863299881:ios:c99748b4389d4499a95338',
    messagingSenderId: '990863299881',
    projectId: 'aion-5a2c7',
    storageBucket: 'aion-5a2c7.firebasestorage.app',
    iosBundleId: 'com.rejrak.wos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGzQS-xL8V1LqOpkTj-MbrQRC9XYhnMZ4',
    appId: '1:990863299881:web:a912c2f33a25d973a95338',
    messagingSenderId: '990863299881',
    projectId: 'aion-5a2c7',
    authDomain: 'aion-5a2c7.firebaseapp.com',
    storageBucket: 'aion-5a2c7.firebasestorage.app',
  );
}
